=== daniilpass/ya-home/packages/shared/src/schemas/home/plan.json
{
  "$schema": "https://json-schema.org/draft/2019-09/schema",
  "title": "Plan",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "id": {
      "type": "number"
    },
    "background": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "color": {
          "type": "string"
        },
        "image": {
          "type": "string"
        }
      },
      "required": ["color"]
    },
    "width": {
      "type": "number"
    },
    "height": {
      "type": "number"
    },
    "devices": {
      "type": "object",
      "additionalProperties": {
        "type": "object",
        "additionalProperties": false,
        "properties": {
          "id": {
            "type": "string"
          },
          "name": {
            "type": "string"
          },
          "type": {
            "type": "string"
          },
          "position": {
            "$ref": "#/$defs/point"
          },
          "icon": {
            "type": "string"
          },
          "area": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
              "bulbsLinePoints": {
                "type": "array",
                "items": {
                  "$ref": "#/$defs/point"
                }
              },
              "shadowPoints": {
                "type": "array",
                "items": {
                  "$ref": "#/$defs/point"
                }
              },
              "shadowMaskPoints": {
                "type": "array",
                "items": {
                  "$ref": "#/$defs/point"
                }
              }
            }
          }
        },
        "required": ["id", "name", "type", "position"]
      }
    }
  },
  "required": ["width", "height", "background", "devices"],
  "$defs": {
    "point": {
      "type": "array",
      "contains": {
        "type": "number"
      },
      "minContains": 2,
      "maxContains": 2
    }
  }
}

=== daniilpass/ya-home/packages/api/src/demo/plan.json
{
    "background": {
      "color": "#97cbfe",
      "image": "104ce32c-5235-4ae4-8b3e-c7b3fa1b4e60"
    },
    "width": 1920,
    "height": 1081,
    "devices": {
      "4d3e0a3b-f544-4a1b-9428-3b5a69551efc": {
        "id": "4d3e0a3b-f544-4a1b-9428-3b5a69551efc",
        "name": "Выключатель в кабинете Д",
        "type": "switch",
        "position": [
          780,
          890
        ],
        "icon": "bulb",
        "area": {
          "shadowPoints": [
            [
              617,
              796
            ],
            [
              917,
              796
            ],
            [
              917,
              1036
            ],
            [
              617,
              1036
            ]
          ]
        }
      },
      "bd5b5118-ed3b-4085-8687-c60271f9aec2": {
        "id": "bd5b5118-ed3b-4085-8687-c60271f9aec2",
        "name": "Выключатель в кабинете А",
        "type": "switch",
        "position": [
          1065,
          890
        ],
        "icon": "bulb",
        "area": {
          "shadowPoints": [
            [
              930,
              796
            ],
            [
              1240,
              796
            ],
            [
              1240,
              1040
            ],
            [
              930,
              1040
            ]
          ]
        }
      },
      "636f243b-3e8f-4b1f-9d5f-a9dd43f353c6": {
        "id": "636f243b-3e8f-4b1f-9d5f-a9dd43f353c6",
        "name": "Выключатель люстра кухня",
        "type": "switch",
        "position": [
          1365,
          730
        ],
        "icon": "bulb",
        "area": {
          "bulbsLinePoints": [
            [
              1365,
              730
            ],
            [
              1365,
              830
            ]
          ],
          "shadowPoints": [
            [
              1325,
              688
            ],
            [
              1404,
              688
            ],
            [
              1404,
              857
            ],
            [
              1325,
              857
            ]
          ]
        }
      },
      "384d283d-c70d-4fc4-beb7-8e13825994ac": {
        "id": "384d283d-c70d-4fc4-beb7-8e13825994ac",
        "name": "Выключатель свет кухня",
        "type": "switch",
        "position": [
          1362,
          653
        ],
        "icon": "bulb",
        "area": {
          "bulbsLinePoints": [
            [
              1362,
              653
            ],
            [
              1450,
              653
            ],
            [
              1450,
              914
            ],
            [
              1277,
              914
            ],
            [
              1277,
              653
            ],
            [
              1362,
              653
            ]
          ],
          "shadowPoints": [
            [
              1250,
              784
            ],
            [
              1252,
              784
            ],
            [
              1252,
              640
            ],
            [
              1252,
              470
            ],
            [
              1450,
              470
            ],
            [
              1450,
              544
            ],
            [
              1639,
              544
            ],
            [
              1637,
              1039
            ],
            [
              1250,
              1039
            ]
          ],
          "shadowMaskPoints": [
            [
              1325,
              688
            ],
            [
              1404,
              688
            ],
            [
              1404,
              857
            ],
            [
              1325,
              857
            ]
          ]
        }
      },
      "81924c48-3d90-4b9b-95ad-a9df8845b327": {
        "id": "81924c48-3d90-4b9b-95ad-a9df8845b327",
        "name": "Выключатель левый трэк",
        "type": "switch",
        "position": [
          1180,
          530
        ],
        "icon": "bulb",
        "area": {
          "bulbsLinePoints": [
            [
              1180,
              530
            ],
            [
              740,
              530
            ],
            [
              740,
              585
            ]
          ],
          "shadowPoints": [
            [
              618,
              470
            ],
            [
              1252,
              470
            ],
            [
              1252,
              625
            ],
            [
              618,
              625
            ]
          ]
        }
      },
      "735de64f-469d-4078-ad9f-d8ee10e10a53": {
        "id": "735de64f-469d-4078-ad9f-d8ee10e10a53",
        "name": "Выключатель правый трэк",
        "type": "switch",
        "position": [
          740,
          690
        ],
        "icon": "bulb",
        "area": {
          "bulbsLinePoints": [
            [
              740,
              690
            ],
            [
              1180,
              690
            ],
            [
              1180,
              635
            ]
          ],
          "shadowPoints": [
            [
              618,
              625
            ],
            [
              1252,
              625
            ],
            [
              1252,
              785
            ],
            [
              618,
              785
            ]
          ]
        }
      },
      "343f829b-d835-4a74-8215-f9fadae29603": {
        "id": "343f829b-d835-4a74-8215-f9fadae29603",
        "name": "Выключатель свет спальня",
        "type": "switch",
        "position": [
          570,
          775
        ],
        "icon": "bulb",
        "area": {
          "bulbsLinePoints": [
            [
              570,
              775
            ],
            [
              570,
              920
            ],
            [
              440,
              920
            ],
            [
              440,
              590
            ],
            [
              570,
              590
            ],
            [
              570,
              775
            ]
          ],
          "shadowPoints": [
            [
              605,
              1037
            ],
            [
              280,
              1037
            ],
            [
              280,
              546
            ],
            [
              605,
              546
            ]
          ]
        }
      },
      "d6e5f3ef-23fd-4655-8a70-e35d1b9c22e6": {
        "id": "d6e5f3ef-23fd-4655-8a70-e35d1b9c22e6",
        "name": "Выключатель свет ванная",
        "type": "switch",
        "position": [
          435,
          415
        ],
        "icon": "bulb",
        "area": {
          "shadowPoints": [
            [
              482,
              534
            ],
            [
              282,
              534
            ],
            [
              282,
              349
            ],
            [
              341,
              349
            ],
            [
              341,
              262
            ],
            [
              482,
              262
            ],
            [
              482,
              534
            ]
          ]
        }
      },
      "ef20fa64-8ba2-4951-be45-f8cb95487957": {
        "id": "ef20fa64-8ba2-4951-be45-f8cb95487957",
        "name": "Выключатель свет гардеробная",
        "type": "switch",
        "position": [
          550,
          195
        ],
        "icon": "bulb",
        "area": {
          "shadowPoints": [
            [
              604,
              248
            ],
            [
              416,
              248
            ],
            [
              416,
              169
            ],
            [
              282,
              169
            ],
            [
              282,
              79
            ],
            [
              604,
              79
            ]
          ]
        }
      },
      "6f779d22-7c74-4622-bf65-1f595eb0b0c2": {
        "id": "6f779d22-7c74-4622-bf65-1f595eb0b0c2",
        "name": "Выключатель проход в спальне",
        "type": "switch",
        "position": [
          570,
          415
        ],
        "icon": "bulb",
        "area": {
          "bulbsLinePoints": [
            [
              570,
              510
            ],
            [
              570,
              320
            ]
          ],
          "shadowPoints": [
            [
              605,
              546
            ],
            [
              496,
              546
            ],
            [
              496,
              262
            ],
            [
              605,
              262
            ]
          ]
        }
      },
      "6ac9a76b-fce3-40d0-9be1-80c9cad59007": {
        "id": "6ac9a76b-fce3-40d0-9be1-80c9cad59007",
        "name": "Выключатель свет туалет",
        "type": "switch",
        "position": [
          1505,
          440
        ],
        "icon": "bulb",
        "area": {
          "shadowPoints": [
            [
              1578,
              532
            ],
            [
              1460,
              532
            ],
            [
              1460,
              306
            ],
            [
              1537,
              306
            ],
            [
              1537,
              376
            ],
            [
              1636,
              376
            ],
            [
              1636,
              468
            ],
            [
              1578,
              468
            ]
          ]
        }
      },
      "a0548812-7e7b-49cf-b233-215c664a21d7": {
        "id": "a0548812-7e7b-49cf-b233-215c664a21d7",
        "name": "Вычключатель свет шкаф в коридоре",
        "type": "switch",
        "position": [
          1530,
          125
        ],
